# the PM2 config
---
apps:
  - name: WWW_SERVER
    script: ./dist/server.js
    instances: 1
    exec_mode: cluster
    exec_interpreter: node
    max_memory_restart: 300M
    error: "./temp/logs/err.log"
    output: "./temp/logs/out.log"
    merge_logs: true
    log_date_format: YYYY-MM-DD HH:mm Z
    watch_options:
        usePolling: true
    ignoreWatch:
        - ".git"
        - node_modules
    env:
        NODE_ENV: production
        PORT: 7000


# deploy:
#     production:
#         user: root
#         host: <IP_ADDRESS> # TODO
#         path: /www/
#         ref: origin/master
#         repo: <git>
#         pre-deploy: git reset --hard origin/master && git pull
#         post-deploy: npm install && npm run build && cd ./dist/ && npx pm2 kill && npx pm2 startOrRestart ecosystem.config.yml --env production
